[package]
name = "star_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
rand = "0.8"
rand_chacha = "0.3"
once_cell = "1.21.3"
