[workspace]
resolver = "3"
members = [
    "apps/star_sim_debug",
    "apps/app",
    "apps/population_lab",
    "crates/bug_hunter",
    "crates/bug_hunter/bevy_test_apps",
    "crates/physics/units",
    "crates/simulation",

]
exclude = ["crates/utilities/name_generator"]
default-members = [
    "apps/app",
    "apps/population_lab",
    "crates/simulation",
]
