[package]
name = "star_sim_debug"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
automation_control = { path = "../../crates/automation_control", features = ["driver"] }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
