[package]
name = "color_preview"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19", features = ["bevy_feathers"] }

[lib]
name = "star_sim"
path = "src/lib.rs"

[[bin]]
name = "color_preview"
path = "../color.rs"

[[bin]]
name = "star_sphere"
path = "../star_sphere.rs"

[workspace]
