use super::{
    config::ReportConfig,
    report::{IssueDraft, ReportError},
};
use serde::{Deserialize, Serialize};
use std::{
    fmt, io,
    path::{Path, PathBuf},
    process::Command,
};

/// A prepared GitHub issue report backed by a Markdown draft on disk.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Report {
    title: String,
    draft_path: PathBuf,
}

impl Report {
    /// Builds and writes a portable issue draft from an automation artifact directory.
    pub fn prepare(artifact_dir: impl AsRef<Path>, config: &ReportConfig) -> Result<Self, Error> {
        let artifact_dir = artifact_dir.as_ref();
        let mut draft = IssueDraft::from_artifacts(artifact_dir)?;
        if let Some(generated_by) = config.generated_by.as_deref() {
            draft = draft.with_footer(format!("_Generated by `{generated_by}`._"));
        }
        let title = draft.title.clone();
        let draft_path = draft.write_to(artifact_dir)?;
        Ok(Self { title, draft_path })
    }

    /// Returns the outcome for a locally prepared draft without contacting GitHub.
    pub fn draft(self) -> Outcome {
        Outcome::Drafted {
            title: self.title,
            path: self.draft_path,
        }
    }

    /// Publishes the prepared draft through the authenticated `gh` CLI.
    ///
    /// An existing open or closed issue with the exact title is returned instead of creating a
    /// duplicate.
    pub fn publish(self) -> Result<Outcome, Error> {
        if let Some(issue) = find_existing_issue(&self.title)? {
            return Ok(Outcome::Existing {
                title: self.title,
                issue,
            });
        }

        let output = Command::new("gh")
            .args(["issue", "create", "--title", &self.title, "--body-file"])
            .arg(&self.draft_path)
            .output()
            .map_err(|error| Error::Start {
                operation: "gh issue create",
                error,
            })?;
        if !output.status.success() {
            return Err(Error::Failed {
                operation: "gh issue create",
                stderr: String::from_utf8_lossy(&output.stderr).trim().to_owned(),
            });
        }
        Ok(Outcome::Created {
            title: self.title,
            url: String::from_utf8_lossy(&output.stdout).trim().to_owned(),
        })
    }
}

/// The externally observable result of preparing or publishing a GitHub report.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum Outcome {
    Drafted { title: String, path: PathBuf },
    Existing { title: String, issue: Issue },
    Created { title: String, url: String },
}

/// The GitHub issue fields returned when exact-title duplicate detection succeeds.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub struct Issue {
    pub number: u64,
    pub title: String,
    pub url: String,
}

/// Errors produced while preparing a draft or invoking the GitHub CLI.
#[derive(Debug)]
pub enum Error {
    Report(ReportError),
    Start {
        operation: &'static str,
        error: io::Error,
    },
    Failed {
        operation: &'static str,
        stderr: String,
    },
    InvalidResponse(serde_json::Error),
}

impl From<ReportError> for Error {
    fn from(error: ReportError) -> Self {
        Self::Report(error)
    }
}

impl fmt::Display for Error {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Report(error) => write!(formatter, "failed to prepare GitHub report: {error}"),
            Self::Start { operation, error } => {
                write!(formatter, "failed to run {operation}: {error}")
            }
            Self::Failed { operation, stderr } => {
                write!(formatter, "{operation} failed: {stderr}")
            }
            Self::InvalidResponse(error) => {
                write!(formatter, "gh issue list returned invalid JSON: {error}")
            }
        }
    }
}

impl std::error::Error for Error {}

fn find_existing_issue(title: &str) -> Result<Option<Issue>, Error> {
    let output = Command::new("gh")
        .args([
            "issue",
            "list",
            "--state",
            "all",
            "--limit",
            "1000",
            "--json",
            "number,title,url",
        ])
        .output()
        .map_err(|error| Error::Start {
            operation: "gh issue list",
            error,
        })?;
    if !output.status.success() {
        return Err(Error::Failed {
            operation: "gh issue list",
            stderr: String::from_utf8_lossy(&output.stderr).trim().to_owned(),
        });
    }
    matching_issue(&output.stdout, title)
}

fn matching_issue(data: &[u8], title: &str) -> Result<Option<Issue>, Error> {
    let issues: Vec<Issue> = serde_json::from_slice(data).map_err(Error::InvalidResponse)?;
    Ok(issues.into_iter().find(|issue| issue.title == title))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_title_matching_uses_typed_github_results() {
        let issue = matching_issue(
            br#"[
                {"number": 7, "title": "other", "url": "https://example.test/7"},
                {"number": 8, "title": "wanted", "url": "https://example.test/8"}
            ]"#,
            "wanted",
        )
        .unwrap()
        .unwrap();

        assert_eq!(issue.number, 8);
        assert_eq!(issue.title, "wanted");
        assert_eq!(issue.url, "https://example.test/8");
    }

    #[test]
    fn malformed_github_results_are_rejected() {
        assert!(matches!(
            matching_issue(br#"[{"number":"not-a-number"}]"#, "wanted"),
            Err(Error::InvalidResponse(_))
        ));
    }
}
