[package]
name = "bevy_test_apps"
version = "0.1.0"
edition = "2024"
publish = false
autobins = false

[dependencies]
bevy = { version = "0.19.1", features = [] }
automation_control = { path = "../", optional = true }
rand = "0.9"

[features]
default = []
automation = ["dep:automation_control"]

[[bin]]
name = "context_menu"
path = "src/bin/context_menu.rs"

[[bin]]
name = "blend_modes"
path = "src/bin/blend_modes.rs"

[[bin]]
name = "mesh_picking"
path = "src/bin/mesh_picking.rs"

[[bin]]
name = "ui_drag_drop"
path = "src/bin/ui_drag_drop.rs"
