pub mod acceleration;
pub mod angle;
pub mod angular_acceleration;
pub mod angular_velocity;
pub mod area;
pub mod compression_modulus;
pub mod density;
pub mod distance;
pub mod elastic_modulus;
pub mod energy;
pub mod force;
pub mod frequency;
pub mod mass;
pub mod momentum;
pub mod power;
pub mod prefix;
pub mod pressure;
pub mod shear_modulus;
pub mod temperature;
pub mod time;
pub mod velocity;
pub mod volume;
pub mod work;

/// Trait for returning the short symbol of a unit.
pub trait UnitSymbol {
    fn symbol() -> String;
}

pub(crate) type Float = f64;

pub use acceleration::*;
pub use angle::*;
pub use angular_acceleration::*;
pub use angular_velocity::*;
pub use area::*;
pub use compression_modulus::*;
pub use density::*;
pub use distance::*;
pub use elastic_modulus::*;
pub use energy::*;
pub use force::*;
pub use frequency::*;
pub use mass::*;
pub use momentum::*;
pub use power::*;
pub use prefix::Atto;
pub use prefix::Centi;
pub use prefix::Deca;
pub use prefix::Deci;
pub use prefix::Exa;
pub use prefix::Femto;
pub use prefix::Giga;
pub use prefix::Hecto;
pub use prefix::Kilo;
pub use prefix::Mega;
pub use prefix::Micro;
pub use prefix::Milli;
pub use prefix::Nano;
pub use prefix::Peta;
pub use prefix::Pico;
pub use prefix::Prefix;
pub use prefix::Tera;
pub use prefix::Yocto;
pub use prefix::Yotta;
pub use prefix::Zepto;
pub use prefix::Zetta;
pub use pressure::*;
pub use shear_modulus::*;
pub use temperature::*;
pub use time::*;
pub use velocity::*;
pub use volume::*;
pub use work::*;
