use serde_json::{Value, json};
use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

const SESSION_TAIL_ENTRIES: usize = 12;
const ISSUE_PREFIX: &str = "[automation failure] ";

pub fn run(args: Vec<String>) -> Result<(), String> {
    let (artifact_dir, create) = parse_args(args)?;
    let failure = read_json(&artifact_dir.join("failure.json"))?;
    let message = failure["message"]
        .as_str()
        .filter(|message| !message.trim().is_empty())
        .ok_or("failure.json has no message")?;
    let title = issue_title(message);
    let body = issue_body(&title, &failure, &artifact_dir)?;
    let draft_path = artifact_dir.join("github-issue.md");
    fs::write(&draft_path, body)
        .map_err(|error| format!("failed to write {}: {error}", draft_path.display()))?;

    if !create {
        println!(
            "{}",
            json!({"status": "drafted", "title": title, "path": draft_path})
        );
        return Ok(());
    }

    if let Some(issue) = find_existing_issue(&title)? {
        println!(
            "{}",
            json!({"status": "existing", "title": title, "issue": issue})
        );
        return Ok(());
    }

    let output = Command::new("gh")
        .args(["issue", "create", "--title", &title, "--body-file"])
        .arg(&draft_path)
        .output()
        .map_err(|error| format!("failed to run gh issue create: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "gh issue create failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    println!(
        "{}",
        json!({
            "status": "created",
            "title": title,
            "url": String::from_utf8_lossy(&output.stdout).trim(),
        })
    );
    Ok(())
}

fn parse_args(args: Vec<String>) -> Result<(PathBuf, bool), String> {
    let mut args = args.into_iter();
    let artifact_dir = args
        .next()
        .map(PathBuf::from)
        .ok_or("usage: star_sim_debug report ARTIFACT_DIR [--create]")?;
    let create = match args.next().as_deref() {
        None => false,
        Some("--create") => true,
        Some(option) => return Err(format!("unknown report option {option:?}")),
    };
    if let Some(option) = args.next() {
        return Err(format!("unexpected report argument {option:?}"));
    }
    Ok((artifact_dir, create))
}

fn issue_title(message: &str) -> String {
    let message = message
        .lines()
        .next()
        .unwrap_or("automation run failed")
        .trim();
    let mut title = format!("{ISSUE_PREFIX}{message}");
    if title.chars().count() > 120 {
        title = title.chars().take(117).collect::<String>() + "...";
    }
    title
}

fn issue_body(title: &str, failure: &Value, artifact_dir: &Path) -> Result<String, String> {
    let recent = read_optional(&artifact_dir.join("recent.log"))?;
    let session = read_optional(&artifact_dir.join("session.jsonl"))?;
    let session_tail = session
        .lines()
        .rev()
        .take(SESSION_TAIL_ENTRIES)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
        .collect::<Vec<_>>()
        .join("\n");
    let kind = failure["kind"].as_str().unwrap_or("unknown");
    let cli_error = failure["cli_error"].as_str().unwrap_or("none");
    Ok(format!(
        "# {title}\n\n## Failure\n\n- Kind: `{kind}`\n- CLI error: `{cli_error}`\n\n## Recent Bevy log\n\n````text\n{recent}\n````\n\n## Last protocol activity\n\n````jsonl\n{session_tail}\n````\n\n_Generated by `star_sim_debug report`._\n"
    ))
}

fn find_existing_issue(title: &str) -> Result<Option<Value>, String> {
    let output = Command::new("gh")
        .args([
            "issue",
            "list",
            "--state",
            "all",
            "--limit",
            "1000",
            "--json",
            "number,title,url",
        ])
        .output()
        .map_err(|error| format!("failed to run gh issue list: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "gh issue list failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    let issues: Vec<Value> = serde_json::from_slice(&output.stdout)
        .map_err(|error| format!("gh issue list returned invalid JSON: {error}"))?;
    Ok(issues
        .into_iter()
        .find(|issue| issue["title"].as_str() == Some(title)))
}

fn read_json(path: &Path) -> Result<Value, String> {
    let data =
        fs::read(path).map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    serde_json::from_slice(&data)
        .map_err(|error| format!("invalid JSON in {}: {error}", path.display()))
}

fn read_optional(path: &Path) -> Result<String, String> {
    match fs::read_to_string(path) {
        Ok(value) => Ok(value),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(String::new()),
        Err(error) => Err(format!("failed to read {}: {error}", path.display())),
    }
}
