use automation_control::driver::{ReportConfig, github};
use serde_json::json;
use std::{
    fs,
    path::PathBuf,
    time::{SystemTime, UNIX_EPOCH},
};

#[test]
fn github_report_prepares_a_configured_draft_and_typed_outcome() {
    let artifact_dir = unique_temp_dir();
    fs::create_dir_all(&artifact_dir).expect("artifact directory should be created");
    fs::write(
        artifact_dir.join("failure.json"),
        serde_json::to_vec_pretty(&json!({
            "version": 1,
            "kind": "panic",
            "message": "stellar catalog invariant violated"
        }))
        .unwrap(),
    )
    .unwrap();
    let config = ReportConfig {
        generated_by: Some("star_sim_debug report".into()),
    };

    let report = github::Report::prepare(&artifact_dir, &config)
        .expect("GitHub report draft should be prepared");
    let outcome = report.draft();

    assert_eq!(
        serde_json::to_value(outcome).unwrap(),
        json!({
            "status": "drafted",
            "title": "[automation failure] stellar catalog invariant violated",
            "path": artifact_dir.join("github-issue.md")
        })
    );
    let draft = fs::read_to_string(artifact_dir.join("github-issue.md")).unwrap();
    assert!(draft.ends_with("\n\n_Generated by `star_sim_debug report`._\n"));

    fs::remove_dir_all(artifact_dir).ok();
}

fn unique_temp_dir() -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock should be after the Unix epoch")
        .as_nanos();
    std::env::temp_dir().join(format!(
        "automation-control-github-report-test-{}-{nonce}",
        std::process::id()
    ))
}
