[package]
name = "app"
version = "0.1.0"
edition = "2024"

[features]
default = []
name-generation = ["dep:name_generator"]

[dependencies]
bevy = { version = "0.19.1", features = ["bevy_feathers", "free_camera", "file_watcher"] }
ui = { path = "../../crates/ui" }
simulation = { path = "../../crates/simulation" }

name_generator = { path = "../../crates/utilities/name_generator", optional = true }

[[example]]
name = "name_generator_lab"
required-features = ["name-generation"]
